name: coflow_users_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  animated_switcher_plus: ^1.4.0
  auto_route: ^10.2.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  dotted_border: ^3.1.0
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.1
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lucide_icons_flutter: ^3.1.5
  path_provider: ^2.1.4
  pie_menu: ^3.3.2
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.5+1
  sealed_countries: ^2.8.0
  shared_preferences: ^2.3.3
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  freezed: ^3.2.3
  flutter_gen_runner: ^5.7.0
  auto_route_generator: ^10.2.5
  injectable_generator: ^2.6.2

flutter_gen:
  output: lib/core/gen/
  line_length: 100

  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: CircularStd
      fonts:
        # Book (Regular) - w400
        - asset: assets/fonts/circular_std/CircularStd-Book.ttf
          weight: 400
        # Medium - w500
        - asset: assets/fonts/circular_std/CircularStd-Medium.ttf
          weight: 500
        # Bold - w700
        - asset: assets/fonts/circular_std/CircularStd-Bold.ttf
          weight: 700
